### ISSUE TITLE
Using MKUnits for OS X with CocoaPods

### ISSUE THREAD

**Issue by edasque** [michalkonturek/MKUnits#7]
I am sure I can integrate it by hand but if I try to use MKUnits in an OS X application:
```The platform of the target ... (OS X 10.10) is not compatible with `MKUnits (2.0.0)` which has a minimum requirement of iOS 7.0.```

**Comment by michalkonturek** [comment]
MKUnits was written for iOS only - the podspec specifies only iOS as deployment platform https://github.com/michalkonturek/MKUnits/blob/master/MKUnits.podspec

I don't do OSX apps at the moment, butI guess I will make a deployment target for both iOS and OSX one day.
