### ISSUE TITLE
Swift code example

### ISSUE THREAD

**Issue by edasque** [michalkonturek/MKUnits#8]
Hi, could you provide a code example to use MKUnits in Swift. Specifically I am trying to take a number of bits and transform it to MB.

**Comment by edasque** [comment]
I used the following but I don't love the first line, there has to be a way to create a MKUnit without artificially creating a MKQuantity of that unit and asking for its unit:

```
    let mb_unit = NSNumber.byte_megabyte(8)().unit
    
    let another = NSNumber(float:(results[indexPath.row].length as NSString).floatValue)
    
    let bits = NSNumber.byte_byte(another)()
    
    let mb = bits.convertTo(mb_unit)
```

**Comment by edasque** [comment]
And I found the better way to do it:
```
    var mb_unit = MKByteUnit.megabyte

    let another = NSNumber(float:(results[indexPath.row].length as NSString).floatValue)
    
    let bits = NSNumber.byte_byte(another)()
    
    let mb = bits.convertTo(mb_unit())

```

**Comment by michalkonturek** [comment]
Well, I guess I could add a code sample or a link to my blog entry http://michal.codes/integrating-cocoapods-with-a-swift-project/ how to use MKUnits with Swift.

You need to create extension:

```swift
extension Int {

    func mass_kilogram() -> MKQuantity {
        return MKQuantity.mass_kilogramWithAmount(self)
    }

    func mass_pound() -> MKQuantity {
        return MKQuantity.mass_poundWithAmount(self)
    }
}
```

and then you can do something like that:

```swift
let kilograms = 2.mass_kilogram()
let pounds = 10.mass_pound()
let result = kilograms.add(pounds)
println(result)
```

**Comment by edasque** [comment]
I was hoping for a more thorough coverage, see above

**Comment by michalkonturek** [comment]
README is not a Swift tutorial )

**Comment by edasque** [comment]
No but since the README isn't comprehensive enough to illustrate the API, a good amount of examples are needed, especially since Objective-C-isms don't often translate well in Swift (which is why Alamofire was created for example).
